import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import Draggable from 'react-draggable'
import { Col, Container, Row, Card, Button, Modal } from 'react-bootstrap'
import Chart from '../components/Chart'
import styles from '../styles/Home.module.css'
import { useRouter } from 'next/router'
import CarouselSection from '../components/Carousel'


export default function Home({data}) {
  const [meeting, setMeeting] = useState(false)
  const [student, setStudent] = useState({})
  const [show, setShow] = useState(false)
  const [strategyMaxCount, setStrategyMaxCount] = useState(3)
  const [imageStatue, setImageStatus] = useState(0)
  const router = useRouter()

  const handleStart = () => {

  }

  const handleDrag = () => {

  }
  const handleClose = () => {
    setShow(false)
  }

  const handleStop = () => {

      if (imageStatue < strategyMaxCount)
          setImageStatus(imageStatue + 1)

      console.log(imageStatue)
  }

  const handleShowDetail = (student) => {
    setStudent(student)
    setShow(true)
  }

  const buildUseCases = () => {
    return data.students.map(student => {
      return <Col md={3}>
      <Card style={{ width: '20rem' }}>
        {student.gender=="female" && <Card.Img as={Image} variant="top" src="/images/female.png" width={200} height={200} />}
        {student.gender=="male" && <Card.Img as={Image} variant="top" src="/images/male.jpeg" width={200} height={200} />}
        
        <Card.Body>
          <Card.Title>{student.name}</Card.Title>
          <Card.Text>{student.description}</Card.Text>
          <Button variant="primary" onClick={() => handleShowDetail(student)}>Go somewhere</Button>
        </Card.Body>
      </Card>
    </Col>
    })
  }

  const buildStrategyCards = () =>{
    return data.strategies.map(strategy => {
        return <Col md={3} style={{height:"300px"}}>
          <div className={styles.flipCard}>
            <div className={styles.flipCardInner}>
              <div className={styles.flipCardFront}>
                <h2>{strategy.name}</h2>
              </div>
              <div className={styles.flipCardBack}>{strategy.description}</div>
            </div>
          </div>
      </Col>
    })
  }
  return (
    <div>
      <Head>
        <title>Growth Mindset in the Classroom</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div style={{textAlign:"center", padding:"50px"}}><h3>"It is hard to fail but it is worse never to have tried to succeed." <span style={{fontStyle: "italic"}}>Theodore Roosevelt</span></h3></div>
        <div>
            <div>
              <CarouselSection/>
            </div>
              <div className={styles.section}>
                <Row>
                  <Col md={4}>
                    <Image src="/images/growth-mindset-image.png" width="300" height="350"/>
                  </Col>

                  <Col md={8}>
                      <div style={{padding: "3rem 0"}}>
                        <h3>What is Growth MindSet?</h3>
                        The growth mindset is based on the belief that your basic qualities are things you can cultivate through your efforts. Although people may differ in every which way in their initial talents and aptitudes, interests, or temperaments, everyone can change and grow through application and experience.
                      </div>
                  </Col>

                </Row>
              </div>
              <hr/>
              <div className={styles.section}>
                <Row>
                <Col md={8}>
                      <div style={{padding: "3rem 0"}}>
                        <h3>What is Fixed MindSet?</h3>
                        Believing that your qualities are carved in stone creates an urgency to prove yourself over and over. If you have only a certain amount of intelligence, a certain personality, and a certain moral character, well then you’d better prove that you have a healthy dose of them. It simply wouldn’t do to look or feel deficient in these most basic characteristics.
                      </div>
                  </Col>
                  <Col md={4}>
                    <Image src="/images/fixedmindset.jpg" width="350" height="250"/>
                  </Col>
                </Row>
              </div>
              <hr/>

          <div className={styles.section}>
              <h3>Strategies</h3>
                <Row>
                  <Col md={3} style={{height:"300px"}}>
                      <div className={styles.flipCard}>
                        <div className={styles.flipCardInner}>
                          <div className={styles.flipCardFront}>
                            <h4>Morning Meeting</h4>
                          </div>
                          <div className={styles.flipCardBack}>Morning meeting to build relationship and a safe environment where everyone feels belong and able to take risks.</div>
                        </div>
                      </div>
                  </Col>
                  <Col md={3} style={{height:"300px"}}>
                      <div className={styles.flipCard}>
                        <div className={styles.flipCardInner}>
                          <div className={styles.flipCardFront}>
                            <h4>Survey</h4>
                          </div>
                          <div className={styles.flipCardBack}>I used survey to pre-assess their mindset with the hope to use another survey to assess their growth.</div>
                        </div>
                      </div>
                  </Col>
                  <Col md={3} style={{height:"300px"}}>
                      <div className={styles.flipCard}>
                        <div className={styles.flipCardInner}>
                          <div className={styles.flipCardFront}>
                            <h4>Open-Ended Tasks</h4>
                          </div>
                          <div className={styles.flipCardBack}>This used open-ended tasks that have "High ceiling, low floor" for students to solve problems the way they make sense to them.</div>
                        </div>
                      </div>
                  </Col>
                  <Col md={3} style={{height:"300px"}}>
                      <div className={styles.flipCard}>
                        <div className={styles.flipCardInner}>
                          <div className={styles.flipCardFront}>
                            <h4>Affirmative Words</h4>
                          </div>
                          <div className={styles.flipCardBack}>This used open-ended tasks that have "High ceiling, low floor" for students to solve problems the way they make sense to them.</div>
                        </div>
                      </div>
                  </Col>
                </Row>
              </div>
              <div className={styles.section}>
                <h3>Themes</h3>
                <div>
                  <Row>
                    <Col md={3} style={{height: "200px"}}>
                        <h5>Teach Growth Mindset Explicitly</h5>
                        <div>I notice that teaching the concept of growth mindset helps nurture a growth mindset in the classroom, just like Carol Dweck recommended. Do not assume that every student in your classroom understands the concept.</div>
                        <Button href="/teach-growth-mindset">Read more</Button>
                    </Col>
                    <Col md={3} style={{height: "200px"}}>
                        <h5>Normalize Challenges</h5>
                        <div>Normalizing challenges promote and nurture a growth mindset. Most of my high achiever students have a low tolerance for productive struggle. They get frustrated easily.  I realized that students doing well in all subjects and paying attention does not mean they have a positive mindset towards challenges.</div>
                        <Button href="/normalize-challenges">Read more</Button>
                    </Col>
                    <Col md={3}>
                        <h5>Descriptive Feedback</h5>
                        <div>As simple as feedback sounds, it is not all that easy to give descriptive and timely feedback that meets students' specific and unique needs, particularly with the concept of a growth mindset. Feedback is connected to promoting and nurturing a growth mindset as it helps students know what to do and how to get better at what they are doing. It increases student's engagement and motivation for learning. </div>
                        <Button>Read more</Button>
                    </Col>
                    <Col md={3}>
                        <h5>Teacher's Growth Mindset</h5>
                        <div> Teaching the concept of a growth mindset helps me develop a growth mindset for teaching. This helps me cultivate an environment that promotes and nurtures a positive mindset towards learning, which helps nurture a growth mindset in the classroom.</div>
                        <Button>Read more</Button>
                    </Col>
                  </Row>
                </div>
              </div>
              <div style={{padding:"100px", backgroundColor: "black", color: 'white'}}>
                <Row>
                  <Col md={4}>
                      <div><h3>Strategies</h3></div>
                      <Draggable
                        axis="x"
                        handle=".handle"
                        defaultPosition={{x: 0, y: 0}}
                        position={null}
                        grid={[25, 25]}
                        scale={1}
                        onStart={handleStart}
                        onDrag={handleDrag}
                        onStop={handleStop}>
                        <div className="handle">
                          <div className={styles.draggableDiv}><h3>Morning Meeting</h3></div>
                        </div>
                      </Draggable>

                      <Draggable
                        axis="x"
                        handle=".handle"
                        defaultPosition={{x: 0, y: 0}}
                        position={null}
                        grid={[25, 25]}
                        scale={1}
                        onStart={handleStart}
                        onDrag={handleDrag}
                        onStop={handleStop}>
                        <div className="handle">
                          <div className={styles.draggableDiv}><h3>Affirmative Words</h3></div>
                        </div>
                      </Draggable>

                      <Draggable
                        axis="x"
                        handle=".handle"
                        defaultPosition={{x: 0, y: 0}}
                        position={null}
                        grid={[10, 10]}
                        scale={1}
                        onStart={handleStart}
                        onDrag={handleDrag}
                        onStop={handleStop}>
                        <div className="handle">
                          <div className={styles.draggableDiv}><h3>Teaching on GM</h3></div>
                        </div>
                      </Draggable>
                      <div style={{textAlign: "center"}}><Button size="lg" onClick={() => router.reload()}>Reset</Button></div>

                  </Col>

                  <Col md={8} style={{textAlign: "right"}}>
                    {imageStatue == 0 && <Image className={styles.fadeInImage} src="/images/seed.jpg" width="500" height="300" />}
                    {imageStatue == 1 && <Image className={styles.fadeInImage} src="/images/growing1.jpeg" width="500" height="300" />}
                    {imageStatue == 2 && <Image className={styles.fadeInImage} src="/images/growing2.jpeg" width="500" height="300" />}
                    {imageStatue == 3 && <Image className={styles.fadeInImage} src="/images/grow.jpeg" width="500" height="300" />}

                  </Col>
                </Row>
              </div>

              <div className={styles.section}>
                <h3>Results</h3>
                <div>
                  <Row>
                    <Col>
                        <h4>Growth at the end of Fall term</h4>
                          <Chart/> 
                      <Button variant='success'>See Data</Button>
                    </Col>
                    <Col>
                        <h4>Growth at the end of Fall term</h4>
                      <Image src="/images/chart.jpg" width={650} height={350} />
                      <Button variant='success'>See data</Button>
                    </Col>
                  </Row>
                </div>
              </div>
        </div>

          <Modal 
            show={show} 
            onHide={handleClose} 
            animation={true}
            size="lg"
            aria-labelledby="contained-modal-title-vcenter"
            centered
          >
          <Modal.Header closeButton>
            <Modal.Title>{student.name} Detail</Modal.Title>
          </Modal.Header>
          <Modal.Body>{student.description}</Modal.Body>
          <Modal.Footer>
            <Button variant="secondary" onClick={handleClose}>
              Close
            </Button>
            <Button variant="primary" onClick={handleClose}>
              Save Changes
            </Button>
          </Modal.Footer>
        </Modal>
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}

export async function getStaticProps(context) {
  var data
  try{
    const resp = await fetch("http://localhost:1323")
    if (resp.status == 200) {
      data = await resp.json()
    }
  }catch(ex) {
    console.error("Error while fetching data ", ex)
  }
  return {
    props: data, // will be passed to the page component as props
  }
}